# Assignment 4

### 1. Regularization - Ridge Regression using LSE fit

In [1]:
import numpy as np
X = np.arange(60, 361, 4)
Y = np.sin(np.deg2rad(X))
error = np.random.normal(0,0.01, len(Y))
Y = Y + error
X

array([ 60,  64,  68,  72,  76,  80,  84,  88,  92,  96, 100, 104, 108,
       112, 116, 120, 124, 128, 132, 136, 140, 144, 148, 152, 156, 160,
       164, 168, 172, 176, 180, 184, 188, 192, 196, 200, 204, 208, 212,
       216, 220, 224, 228, 232, 236, 240, 244, 248, 252, 256, 260, 264,
       268, 272, 276, 280, 284, 288, 292, 296, 300, 304, 308, 312, 316,
       320, 324, 328, 332, 336, 340, 344, 348, 352, 356, 360])

In [2]:
from sklearn.preprocessing import PolynomialFeatures
import pandas as pd
pf = PolynomialFeatures(5)
X_n = pf.fit_transform(pd.DataFrame(X))
X_n

array([[1.00000000e+00, 6.00000000e+01, 3.60000000e+03, 2.16000000e+05,
        1.29600000e+07, 7.77600000e+08],
       [1.00000000e+00, 6.40000000e+01, 4.09600000e+03, 2.62144000e+05,
        1.67772160e+07, 1.07374182e+09],
       [1.00000000e+00, 6.80000000e+01, 4.62400000e+03, 3.14432000e+05,
        2.13813760e+07, 1.45393357e+09],
       [1.00000000e+00, 7.20000000e+01, 5.18400000e+03, 3.73248000e+05,
        2.68738560e+07, 1.93491763e+09],
       [1.00000000e+00, 7.60000000e+01, 5.77600000e+03, 4.38976000e+05,
        3.33621760e+07, 2.53552538e+09],
       [1.00000000e+00, 8.00000000e+01, 6.40000000e+03, 5.12000000e+05,
        4.09600000e+07, 3.27680000e+09],
       [1.00000000e+00, 8.40000000e+01, 7.05600000e+03, 5.92704000e+05,
        4.97871360e+07, 4.18211942e+09],
       [1.00000000e+00, 8.80000000e+01, 7.74400000e+03, 6.81472000e+05,
        5.99695360e+07, 5.27731917e+09],
       [1.00000000e+00, 9.20000000e+01, 8.46400000e+03, 7.78688000e+05,
        7.16392960e+07, 

In [3]:
#Scaling input features
from sklearn.preprocessing import StandardScaler
import pandas as pd
ss=StandardScaler()
X_scaled=ss.fit_transform(pd.DataFrame(X_n[:,1:]))
X_new = np.insert(X_scaled, 0, 1, axis=1)
#X_scaled=pd.DataFrame(X_scaled)
#X_scaled.insert(loc=0,value=1.0,name='Ones')
X_new

array([[ 1.        , -1.70940865, -1.28559054, -1.02558916, -0.86344341,
        -0.75593615],
       [ 1.        , -1.66382442, -1.27236123, -1.02218352, -0.86263478,
        -0.75575455],
       [ 1.        , -1.61824019, -1.25827841, -1.01832442, -0.86165945,
        -0.75552142],
       [ 1.        , -1.57265596, -1.24334209, -1.01398353, -0.86049594,
        -0.75522647],
       [ 1.        , -1.52707172, -1.22755226, -1.0091325 , -0.85912147,
        -0.75485818],
       [ 1.        , -1.48148749, -1.21090893, -1.00374299, -0.85751196,
        -0.75440362],
       [ 1.        , -1.43590326, -1.1934121 , -0.99778666, -0.85564204,
        -0.75384848],
       [ 1.        , -1.39031903, -1.17506176, -0.99123517, -0.85348502,
        -0.75317689],
       [ 1.        , -1.3447348 , -1.15585792, -0.98406018, -0.85101293,
        -0.75237145],
       [ 1.        , -1.29915057, -1.13580057, -0.97623334, -0.84819647,
        -0.75141307],
       [ 1.        , -1.25356634, -1.11488972, -0.

In [4]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(X_new,Y,test_size=0.3,random_state=42)

In [5]:
#finding beta's with ridge regression
lamda=0.001
A=X_train.T.dot(X_train)
I=np.identity(A.shape[0])
A1=np.add(A,lamda*I)
B=np.linalg.inv(A1)
C=B.dot(X_train.T)
beta=C.dot(Y_train)
beta

array([-0.08704124,  3.0807645 , -9.18866714,  1.65498191,  7.28321938,
       -3.25010649])

In [6]:
from sklearn.model_selection import train_test_split
X_train2,X_test2,Y_train2,Y_test2 = train_test_split(X_train,Y_train,test_size=0.3,random_state=42)

In [11]:
#tuning the value of lamda (regularization parameter)
from sklearn import metrics
lamda=[1e-7,1e-6,1e-5,1e-4,1e-3,1e-2,1e-1,1,10,100,1000]
R2_score=[]
for i in range(len(lamda)):
    A=X_train2.T.dot(X_train2)
    I=np.identity(A.shape[0])
    A1=np.add(A,lamda[i]*I)
    B=np.linalg.inv(A1)
    C=B.dot(X_train2.T)
    beta2=C.dot(Y_train2)
    Y_predict2=X_test2.dot(beta2)
    R2_score.append(metrics.r2_score(Y_test2,Y_predict2))

In [12]:
max_idx = R2_score.index(max(R2_score))
lamda1 = lamda[max_idx]
lamda1

1e-07

In [13]:
#finding beta's with ridge regression
A=X_train.T.dot(X_train)
I=np.identity(A.shape[0])
A1=np.add(A,lamda1*I)
B=np.linalg.inv(A1)
C=B.dot(X_train.T)
beta=C.dot(Y_train)
beta

array([ -0.08904357,   1.80162566,   0.9990844 , -24.74296175,
        35.29693615, -13.7737882 ])

In [14]:
#Predicting and Testing the ridge regression model
Y_predict=X_test.dot(beta)
from sklearn import metrics
metrics.r2_score(Y_test,Y_predict)

0.9997203916123173

In [15]:
from sklearn.linear_model import Ridge
rr = Ridge(alpha = lamda1)
rr.fit(X_train, Y_train)
Y_predict2 = rr.predict(X_test)
metrics.r2_score(Y_test,Y_predict2)

0.9997203916132781

### 2. PPMI matrix of IMDB Dataset

In [16]:
import pandas as pd
import numpy as  np

In [18]:
#Laod first 1ooo rows of IMDB Dataset
df=pd.read_csv('IMDB_Dataset.csv',nrows=1000)

In [19]:
corpus=[]
for i in range(len(df)):
    corpus.append(df['review'][i])
corpus[0]

"One of the other reviewers has mentioned that after watching just 1 Oz episode you'll be hooked. They are right, as this is exactly what happened with me.<br /><br />The first thing that struck me about Oz was its brutality and unflinching scenes of violence, which set in right from the word GO. Trust me, this is not a show for the faint hearted or timid. This show pulls no punches with regards to drugs, sex or violence. Its is hardcore, in the classic use of the word.<br /><br />It is called OZ as that is the nickname given to the Oswald Maximum Security State Penitentary. It focuses mainly on Emerald City, an experimental section of the prison where all the cells have glass fronts and face inwards, so privacy is not high on the agenda. Em City is home to many..Aryans, Muslims, gangstas, Latinos, Christians, Italians, Irish and more....so scuffles, death stares, dodgy dealings and shady agreements are never far away.<br /><br />I would say the main appeal of the show is due to the fa

In [20]:
corpus_final=[]
for i in range(len(corpus)):
    corpus_final.append(" ".join([word.lower() for word in corpus[i].split() if word.isalpha()]))

In [21]:
document_frequency={}
for i in range(len(corpus_final)):
    word_frequency={}
    for word in corpus_final[i].split():
        word_frequency[word]=1
    document_frequency[i]=word_frequency
document_frequency[0]

{'one': 1,
 'of': 1,
 'the': 1,
 'other': 1,
 'reviewers': 1,
 'has': 1,
 'mentioned': 1,
 'that': 1,
 'after': 1,
 'watching': 1,
 'just': 1,
 'oz': 1,
 'episode': 1,
 'be': 1,
 'they': 1,
 'are': 1,
 'as': 1,
 'this': 1,
 'is': 1,
 'exactly': 1,
 'what': 1,
 'happened': 1,
 'with': 1,
 'first': 1,
 'thing': 1,
 'struck': 1,
 'me': 1,
 'about': 1,
 'was': 1,
 'its': 1,
 'brutality': 1,
 'and': 1,
 'unflinching': 1,
 'scenes': 1,
 'which': 1,
 'set': 1,
 'in': 1,
 'right': 1,
 'from': 1,
 'word': 1,
 'trust': 1,
 'not': 1,
 'a': 1,
 'show': 1,
 'for': 1,
 'faint': 1,
 'hearted': 1,
 'or': 1,
 'pulls': 1,
 'no': 1,
 'punches': 1,
 'regards': 1,
 'to': 1,
 'sex': 1,
 'classic': 1,
 'use': 1,
 'called': 1,
 'nickname': 1,
 'given': 1,
 'oswald': 1,
 'maximum': 1,
 'security': 1,
 'state': 1,
 'it': 1,
 'focuses': 1,
 'mainly': 1,
 'on': 1,
 'emerald': 1,
 'an': 1,
 'experimental': 1,
 'section': 1,
 'prison': 1,
 'where': 1,
 'all': 1,
 'cells': 1,
 'have': 1,
 'glass': 1,
 'fronts': 1,
 

In [22]:
bow=pd.DataFrame(document_frequency)
bow.fillna(0,inplace=True)
bow.head()

0    1    2    3    4    5    6    7    8    9    ...  990  991  \
one        1.0  1.0  1.0  0.0  1.0  1.0  0.0  1.0  1.0  0.0  ...  1.0  1.0   
of         1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  0.0  ...  1.0  1.0   
the        1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  0.0  ...  1.0  1.0   
other      1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  1.0  0.0   
reviewers  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   

           992  993  994  995  996  997  998  999  
one        0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  
of         0.0  1.0  1.0  1.0  0.0  1.0  1.0  1.0  
the        1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  
other      0.0  0.0  0.0  0.0  0.0  1.0  1.0  0.0  
reviewers  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  

[5 rows x 1000 columns]

In [23]:
cooccurrence_matrix=bow.values.dot(bow.values.T)
np.fill_diagonal(cooccurrence_matrix,0)
cooccurrence_matrix

array([[  0., 496., 500., ...,   1.,   1.,   1.],
       [496.,   0., 950., ...,   1.,   1.,   1.],
       [500., 950.,   0., ...,   1.,   1.,   1.],
       ...,
       [  1.,   1.,   1., ...,   0.,   1.,   1.],
       [  1.,   1.,   1., ...,   1.,   0.,   1.],
       [  1.,   1.,   1., ...,   1.,   1.,   0.]])

In [24]:
row_totals = (bow.sum(axis=1))
numi = cooccurrence_matrix*1000
A = np.outer(row_totals.values, row_totals.values.T)
B = numi/A
with np.errstate(divide='ignore'):
    ppmi = np.log(B)
ppmi[np.isinf(ppmi)] = 0
ppmi

array([[0.00000000e+00, 3.70614332e-02, 4.02006966e-03, ...,
        6.91149178e-01, 6.91149178e-01, 6.91149178e-01],
       [3.70614332e-02, 0.00000000e+00, 1.81638547e-03, ...,
        4.70916075e-02, 4.70916075e-02, 4.70916075e-02],
       [4.02006966e-03, 1.81638547e-03, 0.00000000e+00, ...,
        6.01807233e-03, 6.01807233e-03, 6.01807233e-03],
       ...,
       [6.91149178e-01, 4.70916075e-02, 6.01807233e-03, ...,
        0.00000000e+00, 6.90775528e+00, 6.90775528e+00],
       [6.91149178e-01, 4.70916075e-02, 6.01807233e-03, ...,
        6.90775528e+00, 0.00000000e+00, 6.90775528e+00],
       [6.91149178e-01, 4.70916075e-02, 6.01807233e-03, ...,
        6.90775528e+00, 6.90775528e+00, 0.00000000e+00]])